// <auto-generated />
using HiltonMovies.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HiltonMovies.Migrations
{
    [DbContext(typeof(MovieDataContext))]
    [Migration("20230214001003_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("HiltonMovies.Models.MovieResponse", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            category = "Action/Adventure",
                            director = "Troy Duffy",
                            edited = true,
                            lent = "",
                            notes = "",
                            rating = "R",
                            title = "Boondock Saints, The",
                            year = (short)1999
                        },
                        new
                        {
                            MovieID = 2,
                            category = "Action/Adventure",
                            director = "Christopher Nolan",
                            edited = false,
                            lent = "",
                            notes = "",
                            rating = "PG-13",
                            title = "Dark Knight Rises, The",
                            year = (short)2012
                        },
                        new
                        {
                            MovieID = 3,
                            category = "Action/Adventure",
                            director = "John McTiernan",
                            edited = true,
                            lent = "",
                            notes = "",
                            rating = "R",
                            title = "Die Hard",
                            year = (short)1988
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
