// <auto-generated />
using HiltonMovies.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HiltonMovies.Migrations
{
    [DbContext(typeof(MovieDataContext))]
    partial class MovieDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("HiltonMovies.Models.Category", b =>
                {
                    b.Property<int>("categoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .HasColumnType("TEXT");

                    b.HasKey("categoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            categoryID = 1,
                            category = "Action/Adventure"
                        },
                        new
                        {
                            categoryID = 2,
                            category = "Comedy"
                        },
                        new
                        {
                            categoryID = 3,
                            category = "Drama"
                        },
                        new
                        {
                            categoryID = 4,
                            category = "Family"
                        },
                        new
                        {
                            categoryID = 5,
                            category = "Horror/Suspense"
                        },
                        new
                        {
                            categoryID = 6,
                            category = "Miscellaneous"
                        },
                        new
                        {
                            categoryID = 7,
                            category = "Television"
                        },
                        new
                        {
                            categoryID = 8,
                            category = "VHS"
                        });
                });

            modelBuilder.Entity("HiltonMovies.Models.MovieResponse", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("categoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.HasIndex("categoryID");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            categoryID = 1,
                            director = "Troy Duffy",
                            edited = true,
                            lent = "",
                            notes = "",
                            rating = "R",
                            title = "Boondock Saints, The",
                            year = (short)1999
                        },
                        new
                        {
                            MovieID = 2,
                            categoryID = 1,
                            director = "Christopher Nolan",
                            edited = false,
                            lent = "",
                            notes = "",
                            rating = "PG-13",
                            title = "Dark Knight Rises, The",
                            year = (short)2012
                        },
                        new
                        {
                            MovieID = 3,
                            categoryID = 1,
                            director = "John McTiernan",
                            edited = true,
                            lent = "",
                            notes = "",
                            rating = "R",
                            title = "Die Hard",
                            year = (short)1988
                        });
                });

            modelBuilder.Entity("HiltonMovies.Models.MovieResponse", b =>
                {
                    b.HasOne("HiltonMovies.Models.Category", "category")
                        .WithMany()
                        .HasForeignKey("categoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
